/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <gpio.h>
#include <uart.h>
#include <io.h>




int main(void)
{
	gpio_init(INIT_PORT_G);
	gpio_set_dir(GPIO_PORT_G , GPIO_PIN_14 , GPIO_OUTPUT);
	gpio_set_data(GPIO_PORT_G , GPIO_PIN_14 , GPIO_HIGH_VAL);
	gpio_pull(GPIO_PORT_G , GPIO_PIN_14 , GPIO_NO_PULL);

	/*io_write(0x40023800 + 0x30, 0x40);  // IO port G clock enabled
	io_write(0x40021800 + 0x18, 0x2000);  // PG13 set bit
	io_write(0x40021800 + 0x14, 0x2000);  // PG13 set bit
	io_write(0x40021800 + 0x00, 0x4000000);  // PG13 set output mode
	io_write(0x40021800 + 0x0C, 0x0);  // PG13 set No pull-up, pull-down
	io_write(0x40021800 + 0x08, 0x0);  // PG13 set Low speed*/

	usart_init();



	while(1){
//		usart_txData(USART1_REGISTER, '1');
		usart_printf("abc %d %c %s %x", 123, '*', "asd", 10);
	}
    /* Loop forever */
	for(;;);
}
